### ISSUE TITLE
Request left align for Wordpress - Tiled layout  Campus Directory Block

### ISSUE THREAD

**Issue by kanarb** [ucsc/ucsc-2022#153] opened 2022-11-04 21:42 UTC
Becca in INC1384257 asks:

Is there any way to give align left to the campus directory block, one workaround is putting the block in its own column, which still doesn't look great.

The List layout within column would be a great choice except for list layout breaks still breaks on smaller screens.

**Comment by kanarb** [comment] 2022-11-04 21:47
<img width="584" alt="Screen Shot 2022-11-04 at 2 47 01 PM" src="https://user-images.githubusercontent.com/5742093/200079892-e9bd14c9-2412-477e-a87b-0a96940c76d7.png">

**Comment by kanarb** [comment] 2022-11-04 23:02
Here's Kumar's comment. He seems to think this is a longer term fix, not a quick fix. Jason, do you agree?

_The List layout looks pretty good outside of a column and is responsive on smaller screens: https://test-kagarwal.wordpress-dev.ucsc.edu/2022/11/04/cd/

But once its in a column it no longer looks that great: https://test-kagarwal.wordpress-dev.ucsc.edu/2022/11/04/cd-in-column/

I think it could be something to consider as we rewrite the styles, if it could support columns better._

**Comment by superkumario64** [comment] 2022-11-10 16:24
@kanarb the justify-content: start rule is now on prod.

**Comment by knice** [comment] 2022-12-01 18:45
@superkumario64 it looks like you resolved this issue, so we're going to close it. You can re-open it if the issue isn't resolved.

**Closed by knice** 2022-12-01 18:45 UTC
Labels: question
