### ISSUE TITLE
Nagivation Submenu Overlay

### ISSUE THREAD

**Issue by Yingkit22** [ucsc/ucsc-2022#57] opened 2022-06-29 19:19 UTC
There is a UI overlay when using submenus on the navigation blocking out most clickable areas of the other tabs. I believe previously the submenu would span far right of the main tabs.  May be an accessible concern.
<img width="252" alt="Submenu Overlay" src="https://user-images.githubusercontent.com/103080126/176518265-dfa4a050-74cf-4c7c-bde4-be1bff8319b4.png">
.

**Comment by knice** [comment] 2022-07-20 23:37
Hi @Yingkit22, can you test this again and let me know if the issue is still happening? I've made some changes to the main navigation styles recently, so I'm not sure if this issue is still a problem.

**Comment by YScloud22** [comment] 2022-07-21 19:25
Hello @knice, I tested the navigation and it's no longer a problem.

**Comment by knice** [comment] 2022-07-22 17:03
Thank you for checking, @YScloud22! Closing this issue.

**Closed by knice** 2022-07-22 17:03 UTC
Labels: bug
